### ISSUE TITLE
Баг с созданием баззы данных

### ISSUE THREAD

**Issue by Yetty-cod** [Iotwo/YL1#1]
При запуске программы, появилось окно, в котором программа любезно сообщила, что базы данных у меня нет и она сгенерирует новую. После нажатия на кнопку ОК, приложение вылетело с ошибкой, в логе было написано, что мы попытались в цикле for проитерировать NoneType объект

**Comment by Iotwo** [comment]
Стартовый конфигурационный файл не приведён в начальный вид (замечание). Происходит попытка перечисления пустой коллекции при чтении базы.

**Comment by Iotwo** [comment]
Методы load_categories_of_optype и load_operation_types пытались перечислить None, добавлена проверка, что коллекция значений не является NoneType.
